dist: trusty

language: cpp

notifications:
  email: false

# Requirements:
#  - Qt 5.15
#  - CMake 3.12-ish
#  - C++20 compiler: GCC 9/10, Clang 10/11

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_VERSION=3.16

matrix:
  include:
    # GCC on Linux
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      before_install:
        - sudo apt-get update
        - export CC=gcc-9
        - export CXX=g++-9
      install:
        - |
          if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
            CMAKE_URL="http://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.0-Linux-x86_64.tar.gz"
            mkdir -p ${DEPS_DIR}/cmake
            travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
            export PATH=${DEPS_DIR}/cmake/bin:${PATH}
          fi
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - make