dist: trusty

language: cpp

notifications:
  email: false

# Requirements:
#  - Qt 5.15
#  - CMake 3.12-ish
#  - C++20 compiler: GCC 9/10, Clang 10/11

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - CMAKE_VERSION=3.16
    - QT_VERSION_NO_PATCH=5.15
    - QT_VERSION=5.15.0
#    - QT_DIRECTORY=~/Qt

#cache:
#  directories:
#    - ${QT_DIRECTORY}

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - cmake

before_install:
  # Link gcc-6 and g++-6 to their standard commands
  - sudo ln -s /usr/bin/gcc-9 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-9 /usr/local/bin/g++

  # Export CC and CXX to tell cmake which compiler to use
  - export CC=/usr/bin/gcc-9
  - export CXX=/usr/bin/g++-9

  - gcc -v && g++ -v && cmake --version

before_script:
  - g++ --version

  - sudo apt-get update
  - sudo apt-get install build-essential libgl1-mesa-dev

  - |
    if [[ ${TRAVIS_OS_NAME} == "linux" ]]; then
      CMAKE_URL="http://cmake.org/files/v${CMAKE_VERSION}/cmake-${CMAKE_VERSION}.0-Linux-x86_64.tar.gz"
      mkdir -p ${DEPS_DIR}/cmake
      travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  - wget -c http://download.qt.io/archive/qt/${QT_VERSION_NO_PATCH}/${QT_VERSION}/single/qt-everywhere-src-${QT_VERSION}.tar.xz
  - tar xf qt-everywhere-src-${QT_VERSION}.tar.xz
  - cd qt-everywhere-src-${QT_VERSION}
  - ./configure -confirm-license -nomake tests -nomake examples -opensource
  - make
  - sudo make install

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug
  - make