dist: focal # Ubuntu 20.04

language: cpp

notifications:
  email: false

compiler: clang

addons:
  apt:
    packages:
      - cmake
      - qt5-default
      - clang-10
      - ninja-build
      - build-essential
      - libgl1-mesa-dev
      - libboost-dev

before_script:
  - export CC=/usr/bin/clang-10
  - export CXX=/usr/bin/clang++-10

  - sudo apt-get update

  - clang --version
  - cmake --version

script:
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
  - ninja
