dist: trusty

language: cpp

#os:
#  - linux
#  - osx
#
#compiler:
#  - gcc
#  - clang

#addons:
#  apt:
#    packages:

#before_install:
#  - |
#    if [ "$TRAVIS_OS_NAME" = "osx" ];
#      then brew update;
#    fi
#
#  - |
#    if [ "$TRAVIS_OS_NAME" = "linux" ];
#      sudo apt-get update;
#    fi

#script:
#  - mkdir build
#  - cd build
#  - cmake .. -DCMAKE_BUILD_TYPE=Debug
#  - make
##  - ./testTactile

matrix:
  include:
    # GCC on Linux
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++9
      before_install:
        - export CC=/usr/bin/gcc-9
        - export CXX=/usr/bin/g++-9
        - 
      script:
        - mkdir build
        - cd build
        - cmake .. -DCMAKE_BUILD_TYPE=Debug
        - make