[workspace]
resolver = "3"
members = [
  "crates/*",
]

[workspace.package]
repository = "https://github.com/albin-johansson/tactile"
license = "GPL-3"
version = "0.5.0"
edition = "2024"

# See https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
[workspace.lints.rust]
absolute_paths_not_starting_with_crate = "warn"
ambiguous_negative_literals = "warn"
unnameable_types = "warn"
unused_qualifications = "warn"
unused_results = "warn"
missing_abi = "warn"
missing_copy_implementations = "warn"
non_ascii_idents = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
variant_size_differences = "warn"
