@startuml

!theme blueprint

[foundation] #darkgreen
[core]       #darkgreen
[main]       #darkgreen

package "Plugins" {
  [tactile-yml-format]  #darkred
  [tiled-json-format]   #darkred
  [tiled-xml-format]    #darkred
  [godot3-scene-format] #darkred

  [opengl-renderer] #darkred
  [vulkan-renderer] #darkred
}

database "proto" #black

"tactile-yml-format" -[hidden]- "tiled-json-format"
"tiled-json-format"  -[hidden]- "tiled-xml-format"
"tiled-xml-format"   -[hidden]- "godot3-scene-format"
"opengl-renderer"    -[hidden]- "vulkan-renderer"

"foundation" <.. "core"
"foundation" <.. "main"
"foundation" <.. "Plugins"

"proto" <.. "core"

"core"    <..  "main"
"Plugins" <... "main"

note left of "foundation": Used by all other components.
note right of "main": Provides the main function.\nLocates and loads plugins at runtime.

note "Mandatory components are shown in green.\nPlugin components are shown in red." as N1

@enduml