@startuml

[foundation] #lightgreen
[core]       #lightgreen
[main]       #lightgreen

package "Plugins" {
  [tactile-yml-format]  #lightblue
  [tiled-json-format]   #lightblue
  [tiled-xml-format]    #lightblue
  [godot3-scene-format] #lightblue

  [opengl-renderer] #lightblue
  [vulkan-renderer] #lightblue
}

database "proto"

"tactile-yml-format" -[hidden]- "tiled-json-format"
"tiled-json-format"  -[hidden]- "tiled-xml-format"
"tiled-xml-format"   -[hidden]- "godot3-scene-format"
"opengl-renderer"    -[hidden]- "vulkan-renderer"

"foundation" <.. "core"
"foundation" <.. "main"
"foundation" <.. "Plugins"

"proto" <.. "core"

"core"    <..  "main"
"Plugins" <... "main"

note left of "foundation": This module is used by all other modules.
note right of "main": Provides the main function.\nLocates and loads plugins at runtime.

note "Mandatory modules are shown in green.\nPlugin modules are shown in light blue." as N1

@enduml