name: "CI"

on:
  - "push"

jobs:
  macos-build-and-test:
    runs-on: "macos-26"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Generate build files"
        run: |
          mkdir build
          cd build
          cmake .. --log-level=DEBUG         \
                   -GNinja                   \
                   -DTACTILE_ENABLE_TESTS=ON \
                   -DTACTILE_ENABLE_UBSAN=ON

      - name: "Build"
        working-directory: "./build"
        run: "ninja"

      - name: "Test"
        working-directory: "./build"
        run: "./tactile_tests"

  ubuntu-build-and-test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"

      # https://github.com/libsdl-org/SDL/blob/main/docs/README-linux.md
      - name: "Install build dependencies for SDL"
        run: |
          sudo apt install gnome-desktop-testing
          sudo apt install libasound2-dev       
          sudo apt install libpulse-dev         
          sudo apt install libaudio-dev         
          sudo apt install libfribidi-dev       
          sudo apt install libjack-dev          
          sudo apt install libsndio-dev         
          sudo apt install libx11-dev           
          sudo apt install libxext-dev          
          sudo apt install libxrandr-dev        
          sudo apt install libxcursor-dev       
          sudo apt install libxfixes-dev        
          sudo apt install libxi-dev            
          sudo apt install libxss-dev           
          sudo apt install libxtst-dev          
          sudo apt install libxkbcommon-dev     
          sudo apt install libdrm-dev           
          sudo apt install libgbm-dev           
          sudo apt install libgl1-mesa-dev      
          sudo apt install libgles2-mesa-dev    
          sudo apt install libegl1-mesa-dev     
          sudo apt install libdbus-1-dev         
          sudo apt install libibus-1.0-dev      
          sudo apt install libudev-dev

      - name: "Generate build files"
        run: |
          mkdir build
          cd build
          cmake .. --log-level=DEBUG         \
                   -GNinja                   \
                   -DTACTILE_ENABLE_TESTS=ON \
                   -DTACTILE_ENABLE_UBSAN=ON

      - name: "Build"
        working-directory: "./build"
        run: "ninja"

      - name: "Test"
        working-directory: "./build"
        run: "./tactile_tests"

  windows-build-and-test:
    runs-on: "windows-latest"
    steps:
      - uses: "actions/checkout@v4"

      - name: "Generate build files"
        run: |
          $VsDevCmdBatFile = vswhere -products * -latest -prerelease -find **\Tools\VsDevCmd.bat
          cmd.exe /k $VsDevCmdBatFile
          mkdir build
          cd build
          cmake .. --log-level=DEBUG          `
                   -GNinja                    `
                   -DTACTILE_ENABLE_TESTS=ON  `
                   -DTACTILE_ENABLE_UBSAN=OFF

      - name: "Build"
        working-directory: "./build"
        run: "ninja"

      - name: "Test"
        working-directory: "./build"
        run: "tactile_tests.exe"
