name: "CI: macOS"

on: [ push ]

jobs:
  macos-latest-test:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@main

      - name: Select Xcode version
        run: sudo xcode-select --switch /Applications/Xcode_16.1.app

      - name: Install assets
        working-directory: ./scripts
        run: python3 install_assets.py --skip-fonts

      - name: Build
        run: cargo build --workspace

      - name: Run tests
        working-directory: ./target/debug
        run: cargo test --workspace
