name: "CI: Ubuntu"

on: [ push ]

env:
  DISPLAY: :99.0

jobs:
  ubuntu-latest-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@main
      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install ninja-build \
                           libegl1-mesa-dev \
                           libgles2-mesa-dev \
                           libgl-dev \
                           libasound2-dev \
                           libpulse-dev \
                           libx11-dev \
                           libxmu-dev \
                           libxi-dev \
                           libtool \
                           libltdl-dev \
                           xvfb \
                           pkg-config \
                           automake \
                           autoconf \
                           autoconf-archive \
                           autopoint \
                           gperf \
                           python3-jinja2

      - name: Emulate video device
        run: |
          /sbin/start-stop-daemon --start \
                                  --pidfile /tmp/custom_xvfb_99.pid \
                                  --make-pidfile \
                                  --background \
                                  --exec /usr/bin/Xvfb -- :99 -screen 0 800x600x24 -ac +extension GLX;
          sleep 3

      - name: Install assets
        working-directory: ./scripts
        run: python install_assets.py --skip-fonts

      - name: Build
        run: cargo build --workspace

      - name: Run tests
        working-directory: ./target/debug
        run: cargo test --workspace
