name: "CI: Windows"

on: [ push ]

jobs:
  windows-latest-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main

      - name: Install assets
        working-directory: ./scripts
        run: python install_assets.py --skip-fonts

      - name: Build
        run: cargo build --workspace

      - name: Run tests
        working-directory: ./target/debug
        run: cargo test --workspace
